=== Sri-dinesh/WTS-Laboratory-549/week7_xml_xslt/books.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="catalog">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="book" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="book">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title"     type="xs:string"/>
                <xs:element name="author"    type="xs:string"/>
                <xs:element name="publisher" type="xs:string"/>
                <xs:element name="pages"     type="xs:integer"/>
                <xs:element name="price"     type="xs:decimal"/>
            </xs:sequence>
            <xs:attribute name="course" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Sri-dinesh/WTS-Laboratory-549/week7_xml_xslt/booksdemo.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="books.css"?>
<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="books.xsd">

    <book course="cse">
        <title>Web Technologies</title>
        <author>Kogent Learning Solutions</author>
        <publisher>DreamTech</publisher>
        <pages>1200</pages>
        <price>2552.75</price>
    </book>

    <book course="cse">
        <title>Operating Systems</title>
        <author>Galvin</author>
        <publisher>TMcH</publisher>
        <pages>900</pages>
        <price>850.50</price>
    </book>

    <book course="ece">
        <title>Control Systems</title>
        <author>David Henry</author>
        <publisher>BPB</publisher>
        <pages>600</pages>
        <price>1250.70</price>
    </book>

</catalog>
